name: Use Variables and Secrets
 
on: [workflow_dispatch]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Use variables
        env:
          DB_USER: ${{ vars.ACCESS_VAR }}
        run: |
          echo "Username is $ACCESS_VAR"
 
      - name: Use secrets
        env:
          DB.USERNAME: ${{ secrets.ACCESS_VAR }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "Password length is ${#DB_PASSWORD}"
